### ISSUE TITLE
Replace `container-title`

### ISSUE THREAD

**Issue by nzw0301** [mlresearch/v89#10]
First of all, thank you for hosting JMLR on github. I find a minor issue on this volume, so let me write details.

I think v89's every paper page does not mention that a paper is in Proceedings of AISTATS2019, for example [this](http://proceedings.mlr.press/v89/abbasi-yadkori19a.html). But other AISTATS Proceedings mention it for example, [this is 2018](http://proceedings.mlr.press/v84/choromanski18a.html) and [this in 2020](http://proceedings.mlr.press/v108/pedregosa20a.html).

I think this is because the `_post/*.md`'s `container-title` is different from others:

AISTATS 2020: `Proceedings of the Twenty Third International Conference on Artificial Intelligence and Statistics`
AISTATS 2019 (this volume): `Proceedings of Machine Learning Research`

We might want to replace the values of the attribute with `Proceedings of the Twenty-Second International Conference on Artificial Intelligence and Statistics` for consistency.

I'm happy to send a pull request to do.

Best regards,

**Comment by lawrennd** [comment]
Good spot Kento!

Yes, if you're happy to do the pull request, that would be great.

**Comment by nzw0301** [comment]
Hi @lawrennd, thank you for your response! I sent pull request #11. It's my pleasure and I'm happy to contribute to the machine learning community in any way.
