### ISSUE TITLE
Missing middle initial from author names

### ISSUE THREAD

**Issue by davidar** [mlresearch/v89#3]
A number of author names (including mine) appear to be missing the middle initial in the bibliographic metadata. (It seems like initials without a full stop after them were dropped?) These are the ones I've noticed:

- Alyson K Fletcher
- Andrés F Lopez-Lopera
- Ashok V Makkuva
- Bradley J Gram-Hansen
- David A Roberts
- Edwin V Bonilla 
- Fredrik D Johansson
- Hai S Le
- Henry R Chai
- Jonathan H Huggins
- Kevin K Yang
- Matthew D Hoffman
- Matthew J Holland
- Matthew J Johnson
- Mauricio A Alvarez
- Osman E Dai
- Ricardo B Prudencio
- Tim R Davidson
- Vamsi K Potluru
- Wojciech M Czarnecki

**Comment by lawrennd** [comment]
Thanks David.

Note you can also  request changes by forking on github and submitting a
pull request to any PMLR volume.

@akkiko can you take a look?

Neil

**Comment by davidar** [comment]
I thought that if it was a systematic error then it might be easier for someone with access to the original submissions to fix, but I can certainly submit a PR otherwise.

**Comment by lawrennd** [comment]
You might be right David, unfortunately it’s likely to be a systematic
error in the bib file we generate the pages from or the script we run to
generate them.

However once the files in the _posts directory are created they become the
primary reference and we don’t normally look to re run the script.

Let’s see what Akkiko says.

**Comment by AkikoTakeda** [comment]
Thank you for letting me the issue. 
I generated a bib file from CMT system. So if authors registered their name without their middle names, then the generated PMLR page does not have their middle names, too. Now I'm editing them via a pull request one by one, but it took time because I'm not familiar with github. I have already made some corrections (did pull request) including yours. For others, I'll deal with them when I have time.

**Comment by davidar** [comment]
No worries, I noticed CMT was a bit inconsistent with how it displayed middle initials, so wouldn't surprise me if that's where the problem was. I've submitted a PR to fix all of these names at once, if that helps.

**Comment by lawrennd** [comment]
Thanks David, as mentioned in comments, PR needed periods too! I've added
these now, thanks for all your help!

**Comment by davidar** [comment]
Thanks Neil. No problem, glad I could help
